user = User.create!({ username: "Scott Geryol", email: "scott@example.com" })
user = User.create!({ username: "Kelli Hall", email: "kelli@example.com" })
user = User.create!({ username: "Trey Anastasio", email: "trey@example.com" })

tweet = Tweet.create!({ text: "Yoooo", user_id: 1 })
tweet = Tweet.create!({ text: "Dude", user_id: 1 })
tweet = Tweet.create!({ text: "Sup?", user_id: 1 })
tweet = Tweet.create!({ text: "Whoa.", user_id: 2 })
tweet = Tweet.create!({ text: "Cool", user_id: 2 })
tweet = Tweet.create!({ text: "OK", user_id: 3 })
tweet = Tweet.create!({ text: "No thanks", user_id: 3 })
